### ISSUE TITLE
library "libwhitename.so" not found

### ISSUE THREAD

**Issue by starcheek** [AutelSDK/AndroidAdvanceSample#6]
When cloning and initiallly launching the demo app, i receive 
```2023-06-24 12:17:07.406 5909-5909/com.autel.maxlink E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.autel.maxlink, PID: 5909
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libwhitename.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.autel.internal.autel.authorization.AuthorityManager.<clinit>(AuthorityManager.java:24)
        at com.autel.internal.autel.SDKInitHelper.<init>(SDKInitHelper.java:41)
        at com.autel.internal.autel.SDKInitHelper.init(SDKInitHelper.java:63)
        at com.autel.sdk.Autel.init(Autel.java:49)
        at com.autel.sdksample.TestApplication.onCreate(TestApplication.java:62)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6997)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8176)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)```

**Comment by starcheek** [comment]
This happens in emulatos

**Comment by AutelSDK** [comment]
![企业微信截图_16886101123849](https://github.com/AutelSDK/AndroidAdvanceSample/assets/42387860/b2f64ac6-5f64-4035-94a3-7c3bfcb5ba63)

**Comment by AutelSDK** [comment]
if you meet this problems also then comment the pickFirst line again 
 packagingOptions {
//        pickFirst 'lib/armeabi-v7a/libwhitename.so'
//        pickFirst 'lib/arm64-v8a/libwhitename.so'
//        pickFirst 'lib/armeabi-v7a/libAutelUtil.so'
//        pickFirst 'lib/arm64-v8a/libAutelUtil.so'
    }
