### ISSUE TITLE
App crashes when connected to the drone EVO II Pro V3

### ISSUE THREAD

**Issue by tuannguyenneo** [AutelSDK/AndroidAdvanceSample#8]
**Description:**
App crashes when connected to the drone

**Steps to Reproduce:**
These are my steps to reproduce the issue:
1. Turn the RC on
2. Turn the aircraft on
3. Plug the RC into my MacBook directly
4. Run the example application
5. I heard a sound, then the app crashed

Here is an error log:
```
I/AdrenoGLES-0: QUALCOMM build                   : 85e3412, Ia294594b91
    Build Date                       : 03/27/21
    OpenGL ES Shader Compiler Version: EV031.32.02.07
    Local Branch                     : mybrancheb8f2874-23a9-f1bd-8408-08f1eafda2d0
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r117-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
I/AdrenoGLES-0: Build Config                     : S L 10.0.7 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x005ff114, ME: 0x005ff066
D/AUTEL_USB: callback the usb USB_STATE --com.autel.maxifly.usb.attach
E/AUTEL_USB: callback the usb USB_STATE com.autel.maxifly.usb.attach
D/AUTEL_USB:  ===============startCheckUsbDevice==================
D/AUTEL_USB: callback the usb USB_STATE --com.autel.maxifly.usb.attach
E/AUTEL_USB: callback the usb USB_STATE com.autel.maxifly.usb.attach
D/AUTEL_USB:  ===============stopCheckUsbDevice==================
D/AUTEL_USB:  ===============startCheckUsbDevice==================
E/Autel_SDK: onWifiConnected  isUsbOpened false
W/System: A resource failed to call close. 
I/authority: twiceCheck onFailure 1 -3011invalid request params.
D/ConnectDebug: RcType -> value:6
V/testuuuu: stopBeatMonitor<<<<<<<<<<<<<< true
V/testuuuu: onHeartBeatStatus<<<<<<<<<<<<<< STOP
W/System.err: java.lang.InterruptedException
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2042)
W/System.err:     at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2076)
W/System.err:     at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
W/System.err:     at com.autel.sdk10.AutelNet.AutelMavlinkCore.core.mavlinkconnection.MavLinkConnection$3.run(MavLinkConnection.java:206)
W/System.err:     at java.lang.Thread.run(Thread.java:923)
V/testuuuu: ProductConnectionManager connect  connect  connect  connect
D/ConnectDebug: productChanged true currentVersion null productType EVO_2_ARTOSYN version SERVICE_20 mBaseProduct null
W/CameraManager2: init----->>> 
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.terradrone.rooferdev, PID: 6001
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/reactivex/Observable;
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.initHandler(CameraMessageDisPatcher.java:125)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.<init>(CameraMessageDisPatcher.java:79)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.<init>(CameraMessageDisPatcher.java:58)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher$CameraMessageDisPatcherHolder.<clinit>(CameraMessageDisPatcher.java:87)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher$CameraMessageDisPatcherHolder.access$000(CameraMessageDisPatcher.java:86)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.instance(CameraMessageDisPatcher.java:83)
        at com.autel.camera.protocol.AutelCameraConnectManager.setCameraConnectStatusListener(AutelCameraConnectManager.java:58)
        at com.autel.internal.camera.product.CameraManager.init(CameraManager.java:92)
        at com.autel.internal.product.BaseProductImpl.productInit(BaseProductImpl.java:68)
        at com.autel.internal.product.Evo2AircraftImpl.productInit(Evo2AircraftImpl.java:114)
        at com.autel.internal.autel.SDKInitHelper.initProduct(SDKInitHelper.java:183)
        at com.autel.internal.autel.SDKInitHelper.access$000(SDKInitHelper.java:37)
        at com.autel.internal.autel.SDKInitHelper$1.connect(SDKInitHelper.java:83)
        at com.autel.internal.autel.heartbeat.AbsHeartBeatManager$1.task(AbsHeartBeatManager.java:74)
        at com.autel.internal.sdk.product.datapost.PostRunnable.run(PostRunnable.java:37)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.reactivex.Observable" on path: DexPathList[[dex file "/data/data/com.terradrone.rooferdev/code_cache/.overlay/base.apk/classes11.dex", zip file "/data/app/~~Qz5Cdlf6Nqec1miz_mOk9w==/com.terradrone.rooferdev-uKcK29odF9difIhPh6Qryw==/base.apk"],nativeLibraryDirectories=[/data/app/~~Qz5Cdlf6Nqec1miz_mOk9w==/com.terradrone.rooferdev-uKcK29odF9difIhPh6Qryw==/lib/arm64, /data/app/~~Qz5Cdlf6Nqec1miz_mOk9w==/com.terradrone.rooferdev-uKcK29odF9difIhPh6Qryw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.initHandler(CameraMessageDisPatcher.java:125) 
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.<init>(CameraMessageDisPatcher.java:79) 
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.<init>(CameraMessageDisPatcher.java:58) 
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher$CameraMessageDisPatcherHolder.<clinit>(CameraMessageDisPatcher.java:87) 
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher$CameraMessageDisPatcherHolder.access$000(CameraMessageDisPatcher.java:86) 
        at com.autel.camera.communication.http.events.CameraMessageDisPatcher.instance(CameraMessageDisPatcher.java:83) 
        at com.autel.camera.protocol.AutelCameraConnectManager.setCameraConnectStatusListener(AutelCameraConnectManager.java:58) 
        at com.autel.internal.camera.product.CameraManager.init(CameraManager.java:92) 
        at com.autel.internal.product.BaseProductImpl.productInit(BaseProductImpl.java:68) 
        at com.autel.internal.product.Evo2AircraftImpl.productInit(Evo2AircraftImpl.java:114) 
        at com.autel.internal.autel.SDKInitHelper.initProduct(SDKInitHelper.java:183) 
        at com.autel.internal.autel.SDKInitHelper.access$000(SDKInitHelper.java:37) 
        at com.autel.internal.autel.SDKInitHelper$1.connect(SDKInitHelper.java:83) 
        at com.autel.internal.autel.heartbeat.AbsHeartBeatManager$1.task(AbsHeartBeatManager.java:74) 
        at com.autel.internal.sdk.product.datapost.PostRunnable.run(PostRunnable.java:37) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/rooferdev/LogCat/2023-07-05-16-05-20.txt: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
W/System.err:     at com.autel.sdksample.TestApplication$ExceptionWriter.getExceptionFileStream(TestApplication.java:164)
W/System.err:     at com.autel.sdksample.TestApplication$ExceptionWriter.saveStackTraceToSD(TestApplication.java:121)
W/System.err:     at com.autel.sdksample.TestApplication$EHandle.uncaughtException(TestApplication.java:94)
W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
W/System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
W/System.err:     at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
W/System.err:     at libcore.io.Linux.open(Native Method)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err:     at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7587)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err: 	... 8 more
I/Process: Sending signal. PID: 6001 SIG: 9
```
![image](https://github.com/AutelSDK/AndroidAdvanceSample/assets/122004255/572564eb-2eb8-4c70-b392-fa97030ec2b7)

**Environment:**
Model: EVO II Pro V3
Firmware:

-   Flight control: V5.0.5.49
-   Camera: V5.0.5.9
-   Remote control: V7.0.2.2
-   Image transmission: V1.1.1.3
-   Remote control image transmission: V1.1.1.4
-   Gimbal: V0.0.0.17
-   Battery: V3.2.1.0
-   Vision Module: V1.0.0.5
-   Sonar: V6.0.1.1
-   ESC1: V1.0.3.11

Commit id (newest on master branch): `8a32fb0c19de02159eadeb9f46acb50146996040`

**Comment by starcheek** [comment]
Add

**Comment by tuannguyenneo** [comment]
@starcheek 
It works for me.
Thanks a lot.

**Comment by tuannguyenneo** [comment]
Hi @starcheek ,
I appreciate your support. So, could I contact you on another platform, such as Skype or email,...? We can discuss more about drone technicals. You can find my email on my profile.
Hoping to get a piece of good news from you.
Thank you so much.

**Comment by starcheek** [comment]
I do not use skype. YOu can email me on ralph.ezerin@gmail.com or discord: starcheek
